# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: en-US
title: Martin Holman
author: Martin Holman
email: me@martinholman.co.nz
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://martinholman.co.nz" # the base hostname & protocol for your site

remote_theme: "mmistakes/so-simple-theme@3.2.0"

# Build settings
markdown: kramdown

permalink: /blog/:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: UA-2950924-5

feed:
  path: atom.xml

footer_links:
  - title: Twitter
    url: https://twitter.com/martin308
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/martin308
    icon: fab fa-github-square
  - title: Instagram
    url: https://instagram.com/martin308
    icon: fab fa-instagram
  - title: LinkedIn
    url: https://linkedin.com/in/martinholman
    icon: fab fa-linkedin
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
