# Site settings
title: Martin Holman
email: me@martinholman.co.nz
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://martinholman.co.nz" # the base hostname & protocol for your site
twitter_username: martin308
github_username:  martin308

# Build settings
markdown: kramdown

permalink: /blog/:year/:month/:day/:title/

google_analytics: UA-2950924-5
